apiVersion: apps/v1
kind: Deployment
metadata:
  name: xesite
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: xesite
  template:
    metadata:
      labels:
        app.kubernetes.io/name: xesite
      annotations:
        keel.sh/policy: "all"
        keel.sh/trigger: poll
        keel.sh/pollSchedule: "@every 5m"
        keel.sh/match-tag: "true"
    spec:
      volumes:
        - name: data
          emptyDir: {}
        - name: anubis
          configMap:
            name: anubis-cfg
        - name: anubis-data
          emptyDir: {}
      containers:
        - name: web
          image: ghcr.io/xe/site/bin:latest
          imagePullPolicy: Always
          env:
            - name: "BIND"
              value: ":3000"
            - name: "INTERNAL_API_BIND"
              value: ":3001"
            - name: "DATA_DIR"
              value: "/xe/data"
            - name: "SITE_URL"
              value: "https://xeiaso.net"
            - name: "ONION_DOMAIN"
              value: "ryelkcbr65vy7pzx26c3rvxya54yuh5ciafth7p6d3p3phpgo2wkznid.onion"
            - name: "REDIRECT_DOMAIN"
              value: "xeiaso.net"
            - name: "PATREON_SAASPROXY_URL"
              value: "http://xesite-patreon-saasproxy.default.svc"
          envFrom:
            - secretRef:
                name: xesite
          ports:
            - containerPort: 3000
              name: http
          volumeMounts:
            - mountPath: "/xe/data"
              name: data
          readinessProbe:
            httpGet:
              path: /healthz
              port: 3001
              httpHeaders:
                - name: X-Kubernetes
                  value: "Is alright, I guess"
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 69
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
              httpHeaders:
                - name: X-Kubernetes
                  value: "Is alright, I guess"
            initialDelaySeconds: 30
            periodSeconds: 30
        - name: anubis
          image: ghcr.io/techarohq/anubis:main
          imagePullPolicy: Always
          env:
            - name: "BIND"
              value: ":8081"
            - name: "DIFFICULTY"
              value: "4"
            - name: "METRICS_BIND"
              value: ":9090"
            - name: "OG_PASSTHROUGH"
              value: "true"
            - name: "POLICY_FNAME"
              value: "/xe/cfg/anubis/botPolicies.yaml"
            - name: "SERVE_ROBOTS_TXT"
              value: "false"
            - name: "TARGET"
              value: "http://localhost:3000"
            # - name: "SLOG_LEVEL"
            #   value: "debug"
          volumeMounts:
            - name: anubis
              mountPath: /xe/cfg/anubis
            - name: anubis-data
              mountPath: /data
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 128Mi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          envFrom:
            - secretRef:
                name: xesite-anubis
            - secretRef:
                name: xesite-anubis-tigris
