resources:
  - 1password.yaml
  - deployment.yaml
  - ingress.yaml
  - machineproxy.yaml
  - onionservice.yaml
  - pod-disruption-budget.yaml
  - service.yaml

configMapGenerator:
  - name: anubis-cfg
    behavior: create
    files:
      - ./anubis/botPolicies.yaml
      - ./anubis/xesite-rss-feeds.yaml
