name: Docker

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - uses: earthly/actions-setup@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: "latest" # or pin to an specific version, e.g. "0.8.1"
      - name: Log into registry 
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        id: build-and-push
        run: |
          earthly --org me-2625 --sat alpha --ci --push +all
      - name: Build Docker image
        if: github.event_name == 'pull_request'
        id: build
        run: |
          earthly --org me-2625 --sat alpha --ci +all
          
  deploy-patreon:
    name: "Deploy patreon-saasproxy"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'cmd/patreon-saasproxy/*.go'
              - 'internal/**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'Earthfile'
      - if: steps.changes.outputs.src == 'true'
        run: flyctl deploy --remote-only -c ./fly/patreon-saasproxy/fly.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
