name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Install Brew dependencies
      run: |
        brew bundle

    - name: cache deno.land dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
        restore-keys: ${{ runner.os }}-deno-
        path: |
          /home/runner/.cache/deno

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Ensure generated code is up to date
      run: |
        go generate ./...
        git diff --exit-code || echo "The current tree is dirty, run 'go generate ./...' to fix it"
