name: Build and deploy site to Tigris

on:
  push:
    branches: [ "never" ]

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Setup Homebrew cellar cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.linuxbrew/Cellar
        key: ${{ runner.os }}-homebrew-cellar-${{ hashFiles('Brewfile.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-homebrew-cellar-
  
    - name: Install Brew dependencies
      run: |
        brew bundle

    - name: Setup Golang caches
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-golang-

    - name: cache deno.land dependencies
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-deno-${{ hashFiles('**/*') }}
        restore-keys: ${{ runner.os }}-deno-
        path: |
          /home/runner/.cache/deno

    - name: Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
        tags: tag:ci

    - name: Build and deploy xesite
      run: |
        go run ./cmd/fabricate-generation
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_ENDPOINT_URL_S3: "https://fly.storage.tigris.dev"
        AWS_REGION: auto
        MIMI_ANNOUNCE_URL: ${{ secrets.MIMI_ANNOUNCE_URL }}
    